export const Products = [
  {
    id: 1,
    nombre: "Call of duty",
    descripcion: "Call of Duty: Infinite Warfare ofrece tres modos de juego únicos: Campaña, Multijugador y Zombies. Campaign es un regreso a las sólidas raíces militares de la franquicia, mientras mira audazmente hacia el futuro, ofreciendo una narrativa rica y atractiva que no se parece a nada en un juego de Call of Duty. El jugador se embarcará en una historia de estilo clásico sobre la guerra a gran escala, ambientada en un futuro donde el conflicto humano se ha extendido por todo nuestro sistema solar",
    categoria: "Accion",
    precio: 1200,
    stock: 3,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612698/imagenes%20para%20mi%20ecommerce/call-of-duty-infinity-war_d8uy72.jpg",
  },
  {
    id: 2,
    nombre: "Mortal Kombat 11",
    descripcion: "¡La experiencia MK11 definitiva! Toma el control de los protectores de Earthrealm en 2 aclamadas campañas de historia que doblan el tiempo mientras compiten para evitar que Kronika retroceda en el tiempo y reinicie la historia. Logro. la lista completa de 37 luchadores, incl. Lluvia, Mileena y Rambo.",
    categoria: "Deportes",
    precio: 1500,
    stock: 1,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612700/imagenes%20para%20mi%20ecommerce/Mortal-Kombat-11-pc-free-download_vzd9ak.jpg",
  },
  {
    id: 3,
    nombre: "Dirt 5",
    descripcion: "DIRT 5 es una experiencia de carreras arcade todoterreno divertida y amplificada creada por Codemasters. Ábrete camino en rutas de todo el mundo, cubriendo grava, hielo, nieve y arena, con una lista de autos que van desde íconos de rally hasta camiones y héroes GT. Con una carrera repleta de estrellas, pantalla dividida para cuatro jugadores, modos en línea innovadores, editor de librea y más características nuevas, DIRT 5 es la próxima generación de carreras extremas.",
    categoria: "Conduccion",
    precio: 1570,
    stock: 5,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612698/imagenes%20para%20mi%20ecommerce/DIRT-5-pc-free-download_vnwoda.jpg",
  },
  {
    id: 4,
    nombre: "Forza horizon 5",
    descripcion: "¡Tu Ultimate Horizon Adventure te espera! Explora los vibrantes y cambiantes paisajes de mundo abierto de México con una acción de conducción ilimitada y divertida en cientos de los mejores autos del mundo.",
    categoria: "Conduccion",
    precio: 1000,
    stock: 7,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612699/imagenes%20para%20mi%20ecommerce/FORZAHORIZON5_w7n447.png",
  },
  {
    id: 5,
    nombre: "Ghostwire",
    descripcion: "Tokio es invadida por fuerzas sobrenaturales mortales, perpetradas por un peligroso ocultista, que hace que la población de Tokio desaparezca en un instante. Alíate con una poderosa entidad espectral en su búsqueda de venganza y domina un poderoso arsenal de habilidades para desentrañar la oscura verdad detrás de la desaparición mientras ENFRENTAS LO DESCONOCIDO en Ghostwire: Tokio.",
    categoria: "Accion",
    precio: 1200,
    stock: 10,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612699/imagenes%20para%20mi%20ecommerce/Ghostwire-Tokyo-pc-free-download_zzkt7k.jpg",
  },
  {
    id: 6,
    nombre: "Riders republic",
    descripcion: "Compite en una multitudinaria carrera en masa: ¡choca, grinda y ábrete paso hasta la meta! Personaliza a tu personaje con estilo para que lo vean tus amigos y tus competidores. Recorre un mundo abierto en bici, esquíes, tabla de snow o traje de alas en modo Carrera o en eventos multijugador.",
    categoria: "Deportes",
    precio: 1200,
    stock: 4,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612699/imagenes%20para%20mi%20ecommerce/riders-republic_nab9ff.jpg",
  },
  {
    id: 7,
    nombre: "State of decay",
    descripcion: "En State of Decay 2, tu base es mucho más que un lugar para que los supervivientes duerman por la noche. Es tu santuario, que ofrece protección contra los hambrientos muertos que acechan más allá del muro. Es tu puesto de mando, donde planeas la estrategia perfecta para matar zombis. Y sobre todo, es una manifestación de tus estrategias personales de supervivencia a largo plazo, que personalizas con tus instalaciones y mejoras idóneas. ¿Construirás una atalaya o plantarás un jardín? ¿Una enfermería o un taller? ¿Cómo decidirás labrar una pequeña civilización en las cenizas de un caótico apocalipsis?",
    categoria: "Accion",
    precio: 1400,
    stock: 5,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612700/imagenes%20para%20mi%20ecommerce/STATE_OF_DECAY_doeogf.png",
  },
  {
    id: 8,
    nombre: "Stray",
    descripcion: "Stray es un juego de aventuras de gatos en tercera persona ambientado en los detallados callejones iluminados con luces de neón de una ciberciudad en decadencia y los turbios entornos de su sórdida parte más vulnerable. Deambula por los alrededores, defiéndete de amenazas imprevistas y resuelve los misterios de este lugar poco acogedor habitado por droides curiosos y criaturas peligrosas",
    categoria: "Aventuras",
    precio: 1200,
    stock: 6,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1677612700/imagenes%20para%20mi%20ecommerce/STRAY_n4qwd8.png",
  },
  {
    id: 9,
    nombre: "Tropico 6",
    descripcion: "¡El presidente está de vuelta! Demuéstrese una vez más como un dictador temido o un estadista amante de la paz en el estado insular de Trópico y conduzca el destino de su propia república bananera a través de cuatro épocas distintas.",
    categoria: "Simulacion",
    precio: 1800,
    stock: 2,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1678377494/Tropico6_mdmkkp.png",
  },
  {
    id: 10,
    nombre: "PC Building Simulator",
    descripcion: "Crea tu propio imperio del PC, desde sencillos diagnósticos y reparaciones hasta lujosas creaciones a medida que harían salivar a cualquier amante de los videojuegos. Con un mercado en expansión lleno de componentes auténticos y con precios realistas, por fin podrás dejar de soñar con ese PC perfecto para salir ahí fuera, montarlo y ver cómo responde en las pruebas de rendimiento.",
    categoria: "Simulacion",
    precio: 1700,
    stock: 8,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1678377494/Pcsimulator_z9uhsr.png",
  },
  {
    id: 11,
    nombre: "Farming Simulator 19",
    descripcion: "Farming Simulator 19 presenta tres mundos abiertos distintos en los que desarrollar y expandir su granja, en solitario o con amigos: pronto se revelarán dos entornos completamente nuevos, así como una versión mejorada del entorno sudamericano, que ha sido revisada Aprovechar las capacidades del nuevo motor.",
    categoria: "Simulacion",
    precio: 1800,
    stock: 5,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1678377494/Farmingsimulator_u1fgjp.png",
  },
  {
    id: 12,
    nombre: "Constructor Made In America",
    descripcion: "Es un remake del clásico título de System3 lanzado en PC y PSX en 1997, donde se ofrece a los aficionados gestionar la ciudad de sus sueños… o de sus pesadillas. Construye tus casas, alquílalas, cuida de tus inquilinos en una producción a cargo de John Widdy, el programador del original así como de Aladdin, y otras figuras claves reunidos para la ocasión con intención de reimaginar la obra con gráficos adaptados, un nuevo punto de vista para la cámara, un equilibrio renovado en la jugabilidad y mapas y modalidades inéditas.",
    categoria: "Simulacion",
    precio: 2000,
    stock: 5,
    img: "https://res.cloudinary.com/dzhlt253x/image/upload/v1678377552/Constructor_ltv9qw.png",
  },
];
